Updated dependencies & minor cleanup
gbalats/jphantom pull request #7
Opened 2020-07-27 06:55 UTC by Col-E

## Dependencies updated

| Name | Old version | Updated version |
|:----:|:--------------------:|:----------------------------------:|
| ASM   |   5.0.3   |   8.0.1       |
| Guava |   18.0   |   29.0-jre   |
| args4j |   2.0.23   |   2.33   |
| logback |   1.0.10   |   1.2.3   |
| slf4j |   1.7.3   |   1.7.30   |
| commons-lang3 | 3.1 | 3.11 |
| annotations | 2.0.1 | 3.0.1 |

## Maven plugins updated

| Name | Old version | Updated version |
|:----:|:--------------------:|:----------------------------------:|
| maven-site-plugin |   3.1   |   3.9.0       |
| nexus-staging-maven-plugin | 1.6.3 | 1.6.8 | 
| maven-source-plugin | 3.0.0 | 3.2.1 | 
| maven-javadoc-plugin | 2.10.3 | 3.2.0 |
| maven-jar-plugin | 3.0.0 | 3.2.0 |
| maven-assembly-plugin | ??? | 3.3.0 | 
| maven-compiler-plugin | 3.5.1 | 3.8.1 |
| findbugs-maven-plugin | 2.5 | 3.0.5 | 

## Other changes

* Extracted logic from driver to allow easy usage of JPhantom as a library with the newly added `JPhantom` class
* Point all ASM version usage to a constant
* Changed project source level from `1.7` to `1.8`
    * Replaced `try { Closable ....` with `try (Closable ...) {`
    * Replaced generics with `<>`
* Removed unused imports
* Added maven version plugin _(used to query plugin/dependency updates)_

2020-07-28 05:38 UTC, gbalats requested changes
Thanks for all the changes! I haven't looked at this code for many years now, so this takes me back a long time ago. :-)

2020-07-28 05:38 UTC, gbalats commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +	public JPhantom(Map<Type, ClassNode> nodes, ClassHierarchy hierarchy, ClassMembers members) {
Why is this passed from outside and not initialized within? The driver doesn't seem to be using it.

2020-07-28 05:38 UTC, gbalats commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +				generated, solution, new MethodDeclarations(solution, phantoms.getLookupTable()));
Is this argument needed? Can the method just read the field?

2020-07-28 17:41 UTC, Col-E commented on src/main/java/org/clyze/jphantom/hier/ClassHierarchies.java
> +				try (InputStream stream = file.getInputStream(entry)) {
Oh sorry, didn't even notice it had auto-tabbed. I assumed it picked up the spaces since it did that for the `pom`. Sure thing

2020-07-28 17:43 UTC, Col-E commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +	public JPhantom(Map<Type, ClassNode> nodes, ClassHierarchy hierarchy, ClassMembers members) {
Looks like an artifact of attempting to keep most of the original design. Ez change.

2020-07-28 18:08 UTC, Col-E commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +				generated, solution, new MethodDeclarations(solution, phantoms.getLookupTable()));
My assumption was that this used to update the generated class files in the output directory with additional methods that were previously missing. 

So with the current changes, the output is in this map. So instead of reading from the output directory it uses `ClassReader cr = new ClassReader(generated.get(p));`. As for the behavior of the method, I passed it so these changes made by the `ClassWriter` in `addMissingMethods` could replace the entry in `generated`.

If I misunderstood the original intent of the method, then the part where the entry is updated can be removed, however I think it is still necessary so the `ClassReader` can read the current output class file.

2020-07-28 18:09 UTC, Col-E commented
> this takes me back a long time ago. :-)

Looking at old code can be a lot of fun :-)

2020-07-28 23:56 UTC, Col-E commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +	public JPhantom(Map<Type, ClassNode> nodes, ClassHierarchy hierarchy, ClassMembers members) {
Ah, looked at it now in the IDE, its because the nodes are populated by reading over the jar's entries. Since the jar is specified in the driver, it made sense to keep the instantiation there.

And since the intention of `JPhantom` is supposed to be independent of file-io _(to be used as a library, for my use case)_ it made sense to be ably to supply it this way.

2020-08-01 08:55 UTC, gbalats requested changes

2020-08-01 08:55 UTC, gbalats commented on src/main/java/org/clyze/jphantom/util/Pair.java
> +                                                  }
Something messed up whitespace on this file. Please fix.

2020-08-01 08:55 UTC, gbalats commented on src/main/java/org/clyze/jphantom/hier/ClassHierarchies.java
> +
What's up with the whitespace changes?

2020-08-01 08:55 UTC, gbalats commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +				generated, solution, new MethodDeclarations(solution, phantoms.getLookupTable()));
I understand the change and it makes sense. I am only asking why do we need the first parameter of addMissingMethods() since generated is also a class field?

2020-08-01 08:55 UTC, gbalats commented on src/main/java/org/clyze/jphantom/Driver.java
>          hierarchy = new UnmodifiableClassHierarchy(hierarchy);
This could also be moved to JPhantom class ctor now.

2020-08-01 08:55 UTC, gbalats commented on src/main/java/org/clyze/jphantom/Driver.java
> +        Map<Type, ClassNode> nodes = new HashMap<>();
This could be changed to Collection<ClassNode> and passed in JPhantom ctor.
The latter could then transform it to this type-to-node Map by applying:
```nodes.put(Type.getObjectType(node.name), node);```

2020-08-01 08:55 UTC, gbalats commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +	public JPhantom(Map<Type, ClassNode> nodes, ClassHierarchy hierarchy, ClassMembers members) {
Oh, yes. Hadn't noticed how nodes was being modified because it was in an unchanged portion of the source. I added another comment about changing the argument type to Collection<ClassNode> (but keeping the `generated` field's type as is).

2020-08-01 09:07 UTC, Col-E commented on src/main/java/org/clyze/jphantom/JPhantom.java
> +				generated, solution, new MethodDeclarations(solution, phantoms.getLookupTable()));
Ah, I didn't catch it was a class field. Will remove the arg.

2020-08-01 09:09 UTC, Col-E commented on src/main/java/org/clyze/jphantom/util/Pair.java
> +                                                  }
😬 Yeah, I had done a replace `\t` with `______________` or something long when I only meant to put `____`. I thought I had reverted that accidental spacing but it looks like it missed a few files

2020-08-01 09:18 UTC, Col-E commented
Bit of an ugly force push there but that should clean up the prior attempt at fixing the incompatible whitespaces. 
Also includes additional suggestions made.

2020-08-01 09:26 UTC, Col-E commented on src/main/java/org/clyze/jphantom/util/Pair.java
> +                                                  }
As a side note, this file seems to have been indented with tabs before this PR when all other files use 4 spaces. 🤔

2020-08-01 20:29 UTC, merged

2020-08-01 20:30 UTC, gbalats commented
Thanks again for the changes!

2020-08-01 20:43 UTC, Col-E commented
👍and thank you for making a great analysis tool

2020-08-05 18:27 UTC, Col-E commented
Side note: I updated the version listed for mvn/gradle in the README in cad18fa7715d0de432674c579f5f6ab89c038c76 

This commit can be reverted or a new artifact can be published to avoid confusion

2020-08-19 02:46 UTC, Col-E commented
Would it be possible to push the changes to a new artifact? I would like to use the updated version in a project.

2020-08-28 11:56 UTC, gbalats commented
I uploaded the new version to sonatype. It should appear on Maven Central within a few hours.

2020-08-28 14:58 UTC, Col-E commented
Thank you 👍